apiVersion: batch/v1
kind: Job
metadata:
  name: stress-job
  namespace: app
spec:
  template:
    spec:
      containers:
      - name: stress
        image: polinux/stress
        args: ["--cpu","2","--vm","1","--vm-bytes","200M","--timeout","60s"]
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "250m", memory: "256Mi" }
      restartPolicy: Never
  backoffLimit: 0
